In [1]:
!pip install --upgrade transformers


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 62.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 21.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 80.6 MB/s eta 0:00:00


In [2]:
model_name = "Haaaaeun/kcbert_hatespeech" #"monologg/kobigbird-bert-base"
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)


Some weights of the model checkpoint at Haaaaeun/kcbert_hatespeech were not used when initializing BigBirdModel: ['classifier.dense.bias', 'classifier.out_proj.bias', 'classifier.out_proj.weight', 'classifier.dense.weight']
- This IS expected if you are initializing BigBirdModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BigBirdModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [69]:
# 입력 문장을 인코딩
inputs = tokenizer.encode_plus(
    "좋아",
    add_special_tokens=True,
    return_attention_mask=True,
    return_tensors="pt"
)


In [70]:

# 모델에 입력값 전달하여 출력값 얻기
outputs = model(
    inputs["input_ids"],
    attention_mask=inputs["attention_mask"]
)


In [71]:
# 출력값 확인
last_hidden_states = outputs.last_hidden_state
print(last_hidden_states)


tensor([[[-0.1885,  0.1630, -0.4417,  ..., -0.0213, -0.0227, -0.2594],
         [-0.1885,  0.1630, -0.4417,  ..., -0.0213, -0.0227, -0.2594],
         [-0.1885,  0.1630, -0.4417,  ..., -0.0213, -0.0227, -0.2594]]],
       grad_fn=<NativeLayerNormBackward0>)


In [72]:
import torch.nn as nn
import torch.nn.functional as F

# 출력층을 정의
num_labels = 2
classifier = nn.Linear(model.config.hidden_size, num_labels)

# 출력층의 입력으로 사용하기 위해 reshape
reshaped_pooling = mean_pooling.view(mean_pooling.size(0), -1)

# 출력층의 입력으로 사용
outputs = classifier(reshaped_pooling)

# 시그모이드 함수를 이용해 0과 1 사이의 값으로 변환
outputs = torch.sigmoid(outputs)

# 최종 예측값(0 또는 1) 얻기
pred = torch.round(outputs)


In [74]:
#이게 0일확률, 1일확률
pred

tensor([[1., 0.]], grad_fn=<RoundBackward0>)

In [ ]:
################################################################################

In [52]:
import torch
import numpy as np
import torch.nn.functional as F


# def new_softmax(a):
#     # 입력 배열에서 logits 추출
#     logits = a.logits.numpy()
    
#     # logits에 softmax 함수 적용
#     c = np.max(logits) 
#     exp_logits = np.exp(logits - c)
#     sum_exp_logits = np.sum(exp_logits)
#     y = (exp_logits / sum_exp_logits) * 100
    
#     return y.tolist()


# 예제 입력 문장
input_text = "안녕하세요. 반갑습니다."

# 입력 문장을 토큰화하여 텐서로 변환
inputs = tokenizer(input_text, return_tensors="pt")
input_ids = inputs["input_ids"]
attention_mask = inputs["attention_mask"]

# 모델의 출력 크기 확인
outputs = model(input_ids=input_ids, attention_mask=attention_mask)
# print(outputs)
probs = F.softmax(outputs.pooler_output, dim=1)
print(probs)
preds = probs.argmax(dim=1)
print(preds)


# logits = outputs.
total = 0
probability = []
# logits = np.round(new_softmax(logits), 3).tolist()
# for logit in logits:
                
#     probability.append(np.round(logit, 3))

# if np.argmax(logits) == 0:  emotion = "general"
# elif np.argmax(logits) == 1: emotion = "hate"
# probability.append(emotion)
# print("prob", probability)
# # 예측 결과 출력
# preds = logits.softmax(dim=-1)
# print(preds)  # tensor([[0.0208, 0.9792]], grad_fn=<SoftmaxBackward>)

tensor([[0.0013, 0.0012, 0.0012, 0.0012, 0.0010, 0.0015, 0.0016, 0.0010, 0.0015,
         0.0011, 0.0015, 0.0015, 0.0013, 0.0012, 0.0011, 0.0014, 0.0016, 0.0016,
         0.0012, 0.0014, 0.0013, 0.0013, 0.0014, 0.0009, 0.0014, 0.0015, 0.0013,
         0.0011, 0.0010, 0.0014, 0.0012, 0.0013, 0.0009, 0.0011, 0.0017, 0.0014,
         0.0011, 0.0023, 0.0012, 0.0009, 0.0016, 0.0011, 0.0016, 0.0010, 0.0013,
         0.0014, 0.0013, 0.0013, 0.0017, 0.0011, 0.0016, 0.0012, 0.0018, 0.0014,
         0.0010, 0.0013, 0.0013, 0.0011, 0.0011, 0.0011, 0.0013, 0.0020, 0.0016,
         0.0015, 0.0009, 0.0013, 0.0017, 0.0015, 0.0015, 0.0011, 0.0012, 0.0013,
         0.0012, 0.0017, 0.0016, 0.0012, 0.0016, 0.0009, 0.0010, 0.0010, 0.0010,
         0.0008, 0.0013, 0.0016, 0.0013, 0.0012, 0.0010, 0.0009, 0.0014, 0.0017,
         0.0013, 0.0015, 0.0013, 0.0015, 0.0012, 0.0013, 0.0011, 0.0012, 0.0014,
         0.0012, 0.0013, 0.0013, 0.0013, 0.0019, 0.0010, 0.0013, 0.0011, 0.0010,
         0.0011, 0.0011, 0.0

In [ ]:
outputs.last_hidden_state.shape

torch.Size([1, 7, 768])

In [ ]:
import torch
import numpy as np

def new_softmax(a):
    # 입력 배열에서 logits 추출
    logits = a
    
    # logits에 softmax 함수 적용
    y = torch.nn.functional.softmax(logits, dim=-1)
    return y.tolist()


# 예제 입력 문장
input_text = ""

# 입력 문장을 토큰화하여 텐서로 변환
inputs = tokenizer(input_text, return_tensors="pt")
input_ids = inputs["input_ids"]
attention_mask = inputs["attention_mask"]

# 모델의 출력 크기 확인
outputs = model(input_ids=input_ids, attention_mask=attention_mask)
logits = outputs.last_hidden_state
total = 0
probability = []
logits = np.round(new_softmax(logits), 3).tolist()
for logit in logits:
    probability.append(logit)

print("logits")
print(logits)
print(np.max(logits))
if np.max(logits) <= 0.5:
    emotion = "general"
elif np.max(logits) >= 0.5:
    emotion = "hate"

probability.append(emotion)
print("prob", probability)

# 예측 결과 출력
preds = torch.softmax(torch.tensor(logits), dim=-1)
print(preds)  # tensor([[0.0208, 0.9792]], grad_fn=<SoftmaxBackward>)
print(emotion)

logits
[[[0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.002, 0.002, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.003, 0.001, 0.002, 0.002, 0.003, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.002, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0, 0.001, 0.001, 0.001, 0.002, 0.001, 0.002, 0.001, 0.001, 0.001, 0.002, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.002, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.004, 0.002, 0.001, 0.001, 0.002, 0.002, 0.001, 0.001, 0.001, 0.0, 0.001, 0.002, 0.001, 0.001, 0.003, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.003, 0.001, 0.001, 0.003, 0.003, 0.001, 0.002, 0.001, 0.001, 0.001, 0.002, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.014, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.002, 0.002, 0.002, 0.001, 0.001, 0.001, 0.001, 0.001, 0.0, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.00